#ifndef RICTUS_MODULE_H
#define RICTUS_MODULE_H

/*
 * Rictus consumes the shared STN-LABZ module ABI from the sibling ABI tree.
 * The shared ABI remains authoritative for binary contract definitions.
 */

#include "../../ABI/includes/module.h"

#define RICTUS_MODULE_ID_MAX STNLABZ_MODULE_ID_MAX
#define RICTUS_MODULE_NAME_MAX STNLABZ_MODULE_NAME_MAX
#define RICTUS_MODULE_COMMAND_NAME_MAX STNLABZ_MODULE_COMMAND_NAME_MAX
#define RICTUS_MODULE_COMMAND_ARGUMENTS_MAX STNLABZ_MODULE_COMMAND_ARGUMENTS_MAX
#define RICTUS_MODULE_COMMAND_SENDER_MAX STNLABZ_MODULE_COMMAND_SENDER_MAX
#define RICTUS_MODULE_COMMAND_ACCOUNT_MAX STNLABZ_MODULE_COMMAND_ACCOUNT_MAX
#define RICTUS_MODULE_MIN_TESTS STNLABZ_MODULE_MIN_TESTS
#define RICTUS_MODULE_API_MAJOR STNLABZ_MODULE_API_MAJOR
#define RICTUS_MODULE_API_MINOR STNLABZ_MODULE_API_MINOR

#define RICTUS_MODULE_STATE_DISCOVERED STNLABZ_MODULE_STATE_DISCOVERED
#define RICTUS_MODULE_STATE_UNVERIFIED STNLABZ_MODULE_STATE_UNVERIFIED
#define RICTUS_MODULE_STATE_TESTING STNLABZ_MODULE_STATE_TESTING
#define RICTUS_MODULE_STATE_QUALIFIED STNLABZ_MODULE_STATE_QUALIFIED
#define RICTUS_MODULE_STATE_ACTIVE STNLABZ_MODULE_STATE_ACTIVE
#define RICTUS_MODULE_STATE_STOPPED STNLABZ_MODULE_STATE_STOPPED
#define RICTUS_MODULE_STATE_FAILED STNLABZ_MODULE_STATE_FAILED
#define RICTUS_MODULE_STATE_QUARANTINED STNLABZ_MODULE_STATE_QUARANTINED
#define RICTUS_MODULE_STATE_UNREGISTERED STNLABZ_MODULE_STATE_UNREGISTERED

#define RICTUS_MODULE_OK STNLABZ_MODULE_OK
#define RICTUS_MODULE_ERR_INVALID_ARGUMENT STNLABZ_MODULE_ERR_INVALID_ARGUMENT
#define RICTUS_MODULE_ERR_INVALID_IDENTITY STNLABZ_MODULE_ERR_INVALID_IDENTITY
#define RICTUS_MODULE_ERR_DUPLICATE STNLABZ_MODULE_ERR_DUPLICATE
#define RICTUS_MODULE_ERR_REGISTRY_FULL STNLABZ_MODULE_ERR_REGISTRY_FULL
#define RICTUS_MODULE_ERR_NOT_FOUND STNLABZ_MODULE_ERR_NOT_FOUND
#define RICTUS_MODULE_ERR_INCOMPATIBLE STNLABZ_MODULE_ERR_INCOMPATIBLE
#define RICTUS_MODULE_ERR_INVALID_STATE STNLABZ_MODULE_ERR_INVALID_STATE
#define RICTUS_MODULE_ERR_QUALIFICATION STNLABZ_MODULE_ERR_QUALIFICATION
#define RICTUS_MODULE_ERR_NOT_QUALIFIED STNLABZ_MODULE_ERR_NOT_QUALIFIED
#define RICTUS_MODULE_ERR_NOT_AUTHORIZED STNLABZ_MODULE_ERR_NOT_AUTHORIZED
#define RICTUS_MODULE_ERR_QUARANTINED STNLABZ_MODULE_ERR_QUARANTINED
#define RICTUS_MODULE_ERR_AUDIT_FULL STNLABZ_MODULE_ERR_AUDIT_FULL
#define RICTUS_MODULE_ERR_START_FAILED STNLABZ_MODULE_ERR_START_FAILED
#define RICTUS_MODULE_ERR_STOP_FAILED STNLABZ_MODULE_ERR_STOP_FAILED

typedef stnlabz_module_state_t rictus_module_state_t;
typedef stnlabz_module_result_t rictus_module_result_t;
typedef stnlabz_module_qualification_result_t rictus_module_qualification_result_t;
typedef stnlabz_module_command_t rictus_module_command_t;
typedef stnlabz_module_command_reply_fn rictus_module_command_reply_fn;
typedef stnlabz_module_command_handler_fn rictus_module_command_handler_fn;
typedef stnlabz_module_send_message_fn rictus_module_send_message_fn;
typedef stnlabz_module_register_command_fn rictus_module_register_command_fn;
typedef stnlabz_module_unregister_command_fn rictus_module_unregister_command_fn;
typedef stnlabz_module_host_t rictus_module_host_t;
typedef stnlabz_module_qualify_fn rictus_module_qualify_fn;
typedef stnlabz_module_start_fn rictus_module_start_fn;
typedef stnlabz_module_stop_fn rictus_module_stop_fn;
typedef stnlabz_module_descriptor_t rictus_module_descriptor_t;

#define rictus_module_state_string stnlabz_module_state_string
#define rictus_module_result_string stnlabz_module_result_string

#endif
