#ifndef RICTUS_MODULE_REGISTRY_H
#define RICTUS_MODULE_REGISTRY_H

#include "rictus_module.h"
#include "../../ABI/includes/module_registry.h"

#define RICTUS_MODULE_REGISTRY_MAX STNLABZ_MODULE_REGISTRY_MAX
#define RICTUS_MODULE_AUDIT_MAX STNLABZ_MODULE_AUDIT_MAX

typedef stnlabz_module_audit_event_t rictus_module_audit_event_t;
typedef stnlabz_module_record_t rictus_module_record_t;
typedef stnlabz_module_audit_entry_t rictus_module_audit_entry_t;
typedef stnlabz_module_registry_t rictus_module_registry_t;

#define rictus_module_registry_init stnlabz_module_registry_init
#define rictus_module_registry_discover stnlabz_module_registry_discover
#define rictus_module_registry_verify stnlabz_module_registry_verify
#define rictus_module_registry_qualify stnlabz_module_registry_qualify
#define rictus_module_registry_restore_qualification stnlabz_module_registry_restore_qualification
#define rictus_module_registry_authorize_activation stnlabz_module_registry_authorize_activation
#define rictus_module_registry_activate stnlabz_module_registry_activate
#define rictus_module_registry_stop stnlabz_module_registry_stop
#define rictus_module_registry_unregister stnlabz_module_registry_unregister
#define rictus_module_registry_fail stnlabz_module_registry_fail
#define rictus_module_registry_quarantine stnlabz_module_registry_quarantine
#define rictus_module_registry_find stnlabz_module_registry_find

#endif
